#!/bin/bash
sudo -v

# Keep-alive: update existing `sudo` time stamp until `osxprep.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "------------------------------"
echo "Updating the OS.  If this requires a restart, run the script again."

export DEBIAN_FRONTEND=noninteractive

apt update && apt upgrade -y && apt autoremove -y